import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, ChevronDown, FileCheck2, Package, Phone, Printer, ShieldCheck } from "lucide-react";
import Layout from "@/components/layout/Layout";
import PageHero from "@/components/shared/PageHero";
import InquiryForm from "@/components/shared/InquiryForm";

interface RowItem { label: string; value: string }
interface StepItem { step: string; title: string; desc: string }
interface ReviewAreaItem { title: string; badge: string; items: string[] }
interface SizeItem { label: string; href: string; badge?: string }
interface Props { heroImage: string; whatsappHref: string; printingRequirements: RowItem[]; orderRequirements: RowItem[]; approvalSteps: StepItem[]; projectReviewAreas: ReviewAreaItem[]; sizes: SizeItem[]; faqs: Array<{ q: string; a: string }> }

function Intro({ label, title, description }: { label: string; title: string; description: string }) { return <div className="max-w-3xl"><p className="text-xs font-semibold uppercase text-amber-700">{label}</p><h2 className="mt-3 text-pretty font-sora text-3xl font-semibold leading-tight text-slate-950 lg:text-[2.5rem]">{title}</h2><p className="mt-4 max-w-[65ch] text-base leading-relaxed text-slate-600 lg:text-lg">{description}</p></div>; }
const orderFacts = [
  { icon: <Package key="spec" />, label: "Specification", value: "Confirmed before pricing" },
  { icon: <FileCheck2 key="art" />, label: "Artwork", value: "Proof and version review" },
  { icon: <Printer key="test" />, label: "Testing", value: "Sample when required" },
  { icon: <ShieldCheck key="repeat" />, label: "Repeat orders", value: "Approved master reference" },
];

export default function CustomPrintedThermalRollsCatalogPage({ heroImage, whatsappHref, printingRequirements, orderRequirements, approvalSteps, projectReviewAreas, sizes, faqs }: Props) {
  return <Layout>
    <PageHero bgImage={heroImage} overlayDir="left" overlayOpacity={66} minHeight="min-h-[380px]" compact breadcrumbs={[{ label: "Home", href: "/" }, { label: "Products", href: "/products" }, { label: "Thermal Paper Rolls", href: "/products/thermal-paper-rolls" }, { label: "Custom Printed" }]} title={<>Custom Printed Thermal Paper Rolls for <span className="text-amber-400">OEM &amp; Private Label Programs</span></>} subtitle="Review the roll specification, artwork, print side, repeat, QR or barcode use, packing and approval route before custom production is quoted." ctas={[{ label: "Send Printing Requirements", href: "#inquiry", variant: "primary" }, { label: "Review Approval Steps", href: "#approval-workflow", variant: "outline" }]} />
    <section className="border-b border-slate-200 bg-white"><div className="container grid grid-cols-2 border-l border-t border-slate-200 py-5 lg:grid-cols-4">{orderFacts.map((fact) => <div key={fact.label} className="flex min-h-20 items-center gap-3 border-b border-r border-slate-200 px-4 py-3"><span className="text-amber-700 [&_svg]:h-5 [&_svg]:w-5">{fact.icon}</span><div><p className="text-xs font-semibold uppercase text-slate-500">{fact.label}</p><p className="mt-1 text-sm font-semibold text-slate-900">{fact.value}</p></div></div>)}</div></section>
    <section className="bg-slate-50"><div className="container grid gap-10 py-12 lg:grid-cols-[0.8fr_1.2fr] lg:py-16"><div><div className="relative aspect-[16/11] overflow-hidden border border-slate-300 bg-white"><Image src={heroImage} alt="Custom printed thermal paper rolls for OEM programs" fill sizes="(max-width:1024px) 100vw,40vw" className="object-cover" /></div><div className="mt-6"><Intro label="Project inputs" title="Approve print and product as one specification" description="Artwork is only usable when the roll, printer, print side, repeat, code use, quantity and packing are defined with it." /></div></div><div data-custom-requirements className="grid gap-8 md:grid-cols-2"><div><h3 className="font-sora text-xl font-semibold">Printing requirements</h3><dl className="mt-4 border-t border-slate-300">{printingRequirements.map((row) => <div key={row.label} className="border-b border-slate-300 py-4"><dt className="text-xs font-semibold uppercase text-slate-500">{row.label}</dt><dd className="mt-2 text-sm leading-relaxed text-slate-800">{row.value}</dd></div>)}</dl></div><div><h3 className="font-sora text-xl font-semibold">Order requirements</h3><dl className="mt-4 border-t border-slate-300">{orderRequirements.map((row) => <div key={row.label} className="border-b border-slate-300 py-4"><dt className="text-xs font-semibold uppercase text-slate-500">{row.label}</dt><dd className="mt-2 text-sm leading-relaxed text-slate-800">{row.value}</dd></div>)}</dl></div></div></div></section>
    <section id="approval-workflow" data-approval-workflow className="scroll-mt-24 border-y border-slate-200 bg-white"><div className="container py-12 lg:py-16"><Intro label="Approval workflow" title="Move from artwork to an approved production reference" description="Each gate resolves a different risk before production is released." /><ol className="mt-8 divide-y divide-slate-200 border-y border-slate-200">{approvalSteps.map((item) => <li key={item.step} className="grid gap-3 py-5 md:grid-cols-[4rem_0.8fr_1.6fr] md:gap-6"><span className="text-sm font-semibold text-amber-700">{item.step}</span><h3 className="font-sora font-semibold text-slate-950">{item.title}</h3><p className="text-sm leading-relaxed text-slate-600">{item.desc}</p></li>)}</ol></div></section>
    <section className="bg-slate-50"><div className="container py-12 lg:py-16"><Intro label="Project review" title="Confirm market requirements without assuming approval" description="Language, tax fields, codes and documents are reviewed against the exact target market and evidence scope." /><div className="mt-8 grid border-l border-t border-slate-300 md:grid-cols-2">{projectReviewAreas.map((area) => <article key={area.title} className="border-b border-r border-slate-300 bg-white p-5"><p className="text-xs font-semibold uppercase text-amber-700">{area.badge}</p><h3 className="mt-2 font-sora text-lg font-semibold">{area.title}</h3><ul className="mt-4 space-y-2">{area.items.map((item) => <li key={item} className="flex gap-2 text-sm text-slate-600"><Check className="mt-0.5 h-4 w-4 flex-none text-amber-700" />{item}</li>)}</ul></article>)}</div></div></section>
    <section className="border-y border-slate-200 bg-white"><div className="container py-12 lg:py-16"><Intro label="Size routes" title="Start from a known format, then confirm the full roll" description="Width alone is not a complete specification. Use these pages as routing references before artwork review." /><div className="mt-8 grid grid-cols-2 border-l border-t border-slate-300 sm:grid-cols-3">{sizes.map((size) => <Link key={size.href} href={size.href} className="min-h-24 border-b border-r border-slate-300 p-4 hover:bg-amber-50"><span className="font-sora font-semibold">{size.label}</span>{size.badge ? <span className="mt-3 block text-xs text-amber-700">{size.badge}</span> : null}</Link>)}</div></div></section>
    <aside data-custom-evidence-boundary className="border-b border-amber-300 bg-amber-50"><div className="container py-5 text-sm leading-relaxed text-slate-700">MOQ, proof route, physical sample, production timing, material claims and destination documents are confirmed after the roll specification, artwork, quantity, packing and evidence scope are reviewed.</div></aside>
    <section className="bg-white"><div className="container grid gap-10 py-12 lg:grid-cols-[0.65fr_1.35fr] lg:py-16"><Intro label="FAQ" title="Custom roll approval questions" description="Answers focused on qualification, testing and repeat-order control." /><div className="border-t border-slate-300">{faqs.map((faq, index) => <details key={faq.q} className="group border-b border-slate-300" open={index === 0}><summary className="flex cursor-pointer list-none gap-4 py-5"><span className="font-semibold text-amber-700">{String(index + 1).padStart(2,"0")}</span><span className="flex-1 font-sora font-semibold">{faq.q}</span><ChevronDown className="h-5 w-5 group-open:rotate-180" /></summary><p className="pb-5 pl-10 text-sm leading-relaxed text-slate-600">{faq.a}</p></details>)}</div></div></section>
    <section id="inquiry" className="scroll-mt-24 bg-slate-50"><div className="container py-12 lg:py-16"><div className="grid overflow-hidden border border-slate-300 bg-white lg:grid-cols-[0.88fr_1.12fr]"><div className="bg-brand-navy p-8 text-white lg:p-10"><p className="text-xs font-semibold uppercase text-amber-300">Custom production brief</p><h2 className="mt-3 font-sora text-3xl font-semibold">Send the inputs needed for review</h2><p className="mt-4 text-sm leading-relaxed text-slate-300">Files can be continued by email or WhatsApp after this structured brief is submitted.</p><a href={whatsappHref} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-amber-300"><Phone className="h-4 w-4" />Continue on WhatsApp</a></div><div className="p-7 lg:p-9"><InquiryForm compact productName="Custom Printed Thermal Paper Rolls" initialMessage={`Roll specification / current sample:
Printer model:
Print side:
Artwork and language:
Colors and repeat:
Live-print area:
QR / barcode use:
Quantity by SKU:
Packing:
Destination:
Document requirement:`} /></div></div></div></section>
  </Layout>;
}
