onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true
