import Link from "next/link";
import { ArrowRight, Check, ChevronDown, Phone } from "lucide-react";
import Layout from "@/components/layout/Layout";
import PageHero from "@/components/shared/PageHero";
import InquiryForm from "@/components/shared/InquiryForm";

interface ServicePath { id: "rolls" | "labels"; title: string; description: string; href: string; cta: string }
interface ServiceStep { step: string; title: string; description: string }
interface Props { heroImage: string; whatsappHref: string; productPaths: ServicePath[]; steps: ServiceStep[]; faqs: Array<{ q: string; a: string }> }
function Intro({ label, title, description }: { label: string; title: string; description: string }) { return <div className="max-w-3xl"><p className="text-xs font-semibold uppercase text-amber-700">{label}</p><h2 className="mt-3 text-pretty font-sora text-3xl font-semibold leading-tight text-slate-950 lg:text-[2.5rem]">{title}</h2><p className="mt-4 max-w-[65ch] text-base leading-relaxed text-slate-600 lg:text-lg">{description}</p></div>; }

export default function CustomPrintingServicePage({ heroImage, whatsappHref, productPaths, steps, faqs }: Props) {
  return <Layout>
    <PageHero bgImage={heroImage} overlayDir="left" overlayOpacity={66} minHeight="min-h-[360px]" compact breadcrumbs={[{ label: "Home", href: "/" }, { label: "OEM Services", href: "/oem" }, { label: "Custom Printing" }]} title={<>OEM Printing Services for <span className="text-amber-400">Thermal Rolls &amp; Labels</span></>} subtitle="Choose the product first, then align artwork, versions, proof and sample requirements, packing and repeat-order controls through one OEM service workflow." ctas={[{ label: "Choose a Product Path", href: "#product-paths", variant: "primary" }, { label: "Send an OEM Brief", href: "#inquiry", variant: "outline" }]} />
    <section id="product-paths" className="scroll-mt-24 border-b border-slate-200 bg-white"><div className="container py-12 lg:py-16"><Intro label="Product first" title="Choose the product path before artwork review" description="Rolls and labels require different specifications, materials and printer checks." /><div className="mt-8 grid border-l border-t border-slate-300 md:grid-cols-2">{productPaths.map((path) => <article key={path.id} data-service-product-path={path.id} className="border-b border-r border-slate-300 p-6"><h2 className="font-sora text-xl font-semibold text-slate-950">{path.title}</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">{path.description}</p><Link href={path.href} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-brand-navy">{path.cta}<ArrowRight className="h-4 w-4" /></Link></article>)}</div></div></section>
    <section className="bg-slate-50" data-service-workflow><div className="container py-12 lg:py-16"><Intro label="Service workflow" title="Align product, artwork and approval through one route" description="Each gate produces an agreed input for the next step." /><ol className="mt-8 divide-y divide-slate-200 border-y border-slate-200">{steps.map((step) => <li key={step.step} className="grid gap-3 py-5 md:grid-cols-[4rem_0.8fr_1.6fr] md:gap-6"><span className="text-sm font-semibold text-brand-blue">{step.step}</span><h3 className="font-sora font-semibold text-slate-950">{step.title}</h3><p className="text-sm leading-relaxed text-slate-600">{step.description}</p></li>)}</ol></div></section>
    <section className="border-y border-slate-200 bg-white"><div className="container grid gap-px bg-slate-300 py-12 md:grid-cols-3 lg:py-16">{[["Version control","Tie product, language, artwork and packing versions to the approved reference."],["NDA requests","Confirm confidentiality and neutral-production requirements before files are exchanged."],["Packing control","Confirm labels, pack quantity, carton reference, destination and repeat-order rules."]].map(([title,text]) => <article key={title} className="bg-white p-5"><h3 className="font-sora font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{text}</p></article>)}</div></section>
    <aside data-service-evidence-boundary className="border-b border-amber-300 bg-amber-50"><div className="container py-5 text-sm leading-relaxed text-slate-700">Product feasibility, MOQ, proof route, sample requirement, production timing and documents are confirmed for the selected roll or label specification. This service page does not replace product-specific approval.</div></aside>
    <section className="bg-white"><div className="container grid gap-10 py-12 lg:grid-cols-[0.65fr_1.35fr] lg:py-16"><Intro label="FAQ" title="OEM printing service questions" description="Clarify the workflow before product-specific approval begins." /><div className="border-t border-slate-300">{faqs.map((faq,index) => <details key={faq.q} className="group border-b border-slate-300" open={index===0}><summary className="flex cursor-pointer list-none gap-4 py-5"><span className="font-semibold text-amber-700">{String(index+1).padStart(2,"0")}</span><span className="flex-1 font-sora font-semibold">{faq.q}</span><ChevronDown className="h-5 w-5 group-open:rotate-180" /></summary><p className="pb-5 pl-10 text-sm leading-relaxed text-slate-600">{faq.a}</p></details>)}</div></div></section>
    <section id="inquiry" className="scroll-mt-24 bg-slate-50"><div className="container py-12 lg:py-16"><div className="grid overflow-hidden border border-slate-300 bg-white lg:grid-cols-[0.88fr_1.12fr]"><div className="bg-brand-navy p-8 text-white lg:p-10"><p className="text-xs font-semibold uppercase text-amber-300">OEM service brief</p><h2 className="mt-3 font-sora text-3xl font-semibold">Start with the product and decision inputs</h2><div className="mt-6 space-y-3 text-sm text-slate-200">{["Product and application","Specification and artwork versions","Quantity, packing and destination"].map((item) => <p key={item} className="flex gap-2"><Check className="h-4 w-4 text-amber-400" />{item}</p>)}</div><a href={whatsappHref} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-amber-300"><Phone className="h-4 w-4" />Continue on WhatsApp</a></div><div className="p-7 lg:p-9"><InquiryForm compact productName="OEM Printing Service" initialMessage={`Product: thermal rolls / thermal labels
Application and printer:
Product specification:
Artwork and versions:
Print side / colors / repeat:
Quantity by SKU:
Packing and labeling:
Destination:
Document requirement:
NDA requested: yes / no`} /></div></div></div></section>
  </Layout>;
}
