/**
 * 全站图片槽位注册表
 *
 * - 此文件是图片槽位的「唯一真相」(single source of truth)
 * - 后台「图片管理」从这里读取，显示所有可换图的位置
 * - 代码中所有 getSlotImage("xxx:yyy") 的 slot 参数都必须是 SlotKey 类型
 *   → 拼错会编译报错，永远不可能出现"后台改了前台不变"的情况
 *
 * 新增槽位流程：
 *   1. 在下面的 IMAGE_SLOTS 列表加一条
 *   2. 在页面代码里写 getSlotImage("新-slot-key", fallback)
 *   3. TypeScript 自动保护两边一致
 */

export interface ImageSlot {
  slot: string;          // 槽位 key（与 getSlotImage 的第一个参数一致）
  label: string;         // 中文显示名称
  page: string;          // 所在页面（中文）
  pageUrl: string;       // 预览链接（前台 URL）
  aspect?: string;       // 推荐宽高比（提示用）
  description?: string;  // 用途说明
}

// ⚠️ 严格保持此数组与代码中所有 getSlotImage / getSlotImages 的 slot 参数一致
export const IMAGE_SLOTS = [
  // ===== 首页（来自 src/app/page.tsx）=====
  // 注: 首页 3 张 Hero Banner 改在 /admin/hero 编辑（跟文案/CTA 绑定），不再单独占图片管理槽位
  { slot: "home:product-labels", label: "首页 产品板块 - 标签兜底图", page: "首页", pageUrl: "/", aspect: "4:3", description: "中段产品展示区 - 任何热敏标签产品未单独设置图时使用" },
  { slot: "home:product-rolls", label: "首页 产品板块 - 纸卷兜底图", page: "首页", pageUrl: "/", aspect: "4:3", description: "中段产品展示区 - 任何热敏纸卷产品未单独设置图时使用" },

  // 首页 ② POPULAR SIZES 区域 - 18 个产品独立可换图
  // === Thermal Paper Rolls 组（6 个）===
  { slot: "home:product-pos-receipt-rolls", label: "首页产品-POS Receipt Rolls", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏纸卷组卡片 1" },
  { slot: "home:product-portable-mobile-printer-rolls", label: "首页产品-Portable/Mobile Printer Rolls", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏纸卷组卡片 2" },
  { slot: "home:product-phenol-free-thermal-paper", label: "首页产品-Phenol Free Thermal Paper", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏纸卷组卡片 3" },
  { slot: "home:product-custom-printed-rolls", label: "首页产品-Custom Printed Rolls", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏纸卷组卡片 4" },
  { slot: "home:product-atm-banking-rolls", label: "首页产品-ATM & Banking Rolls", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏纸卷组卡片 5" },
  { slot: "home:product-blank-thermal-rolls", label: "首页产品-Blank Thermal Rolls", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏纸卷组卡片 6" },
  // === Thermal Labels 组（6 个）===
  { slot: "home:product-blank-thermal-labels", label: "首页产品-Blank Thermal Labels", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏标签组卡片 1" },
  { slot: "home:product-4x6-shipping-labels", label: "首页产品-4x6 Shipping Labels", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏标签组卡片 2" },
  { slot: "home:product-barcode-thermal-labels", label: "首页产品-Barcode Thermal Labels", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏标签组卡片 3" },
  { slot: "home:product-custom-printed-labels", label: "首页产品-Custom Printed Labels", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏标签组卡片 4" },
  { slot: "home:product-4x3-thermal-labels", label: "首页产品-4x3 Thermal Labels", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏标签组卡片 5" },
  { slot: "home:product-2x4-thermal-labels", label: "首页产品-2x4 Thermal Labels", page: "首页", pageUrl: "/", aspect: "4:3", description: "首页热敏标签组卡片 6" },
  // === Linerless Labels ===
  { slot: "linerless-labels:hero", label: "无底纸标签聚合页 Hero 图", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:9", description: "品类聚合页首屏，优先使用多卷无底纸标签或实际设备应用图" },
  { slot: "linerless-labels:family-removable", label: "无底纸标签聚合页 - 可移胶", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:9", description: "可移胶或临时标识产品图" },
  { slot: "linerless-labels:family-permanent", label: "无底纸标签聚合页 - 强粘胶", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:9", description: "半永久或永久胶产品图" },
  { slot: "linerless-labels:family-custom", label: "无底纸标签聚合页 - 定制卷材", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:9", description: "定制宽度、纸芯或卷径的卷材图" },
  { slot: "linerless-labels:family-oem", label: "无底纸标签聚合页 - OEM 包装", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:9", description: "OEM 卷标、内包装和外箱图" },
  { slot: "linerless-labels:application-food", label: "无底纸标签聚合页 - 餐饮应用", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:10", description: "预制食品、外卖或餐饮标识场景" },
  { slot: "linerless-labels:application-retail", label: "无底纸标签聚合页 - 零售称重", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:10", description: "零售、称重或价格标签应用场景" },
  { slot: "linerless-labels:application-qsr", label: "无底纸标签聚合页 - 快餐订单", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:10", description: "QSR 订单路由和厨房标识场景" },
  { slot: "linerless-labels:application-logistics", label: "无底纸标签聚合页 - 周转箱物流", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:10", description: "可重复周转箱和临时物流标识场景" },
  { slot: "linerless-labels:quality", label: "无底纸标签聚合页 - 质检与打样", page: "无底纸标签聚合页", pageUrl: "/products/linerless-labels", aspect: "16:10", description: "进纸、切刀、打印、粘合或批量质检场景" },
  { slot: "linerless-3-1-8-x-263:hero", label: "3 1/8 x 263 无底纸标签 - Hero 图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "16:9", description: "产品详情页首屏，优先使用真实卷材与标签成品图" },
  { slot: "linerless-3-1-8-x-263:application", label: "3 1/8 x 263 无底纸标签 - 应用图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "4:3", description: "直接答案和应用场景模块" },
  { slot: "linerless-3-1-8-x-263:quality", label: "3 1/8 x 263 无底纸标签 - 质检图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "4:3", description: "样品、打印、粘合或工厂质检模块" },
  { slot: "linerless-3-1-8-x-263:risk", label: "3 1/8 x 263 无底纸标签 - 采购风险图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "4:3", description: "打印、扫码、粘胶和仓储风险模块" },
  { slot: "linerless-3-1-8-x-263:specification", label: "3 1/8 x 263 无底纸标签 - 规格审核图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "4:3", description: "卷径、纸芯、材料和胶黏规格模块" },
  { slot: "linerless-3-1-8-x-263:workflow", label: "3 1/8 x 263 无底纸标签 - 审批流程图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "4:3", description: "打样、生产和批量订单审批模块" },
  { slot: "linerless-3-1-8-x-263:faq", label: "3 1/8 x 263 无底纸标签 - FAQ 包装图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "4:3", description: "常见采购问题、包装和复购模块" },
  { slot: "linerless-3-1-8-x-263:related-custom", label: "3 1/8 x 263 无底纸标签 - 推荐定制标签图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "4:3", description: "相关产品：定制印刷热敏标签" },
  { slot: "linerless-3-1-8-x-263:related-thermal", label: "3 1/8 x 263 无底纸标签 - 推荐热敏标签图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "4:3", description: "相关产品：热敏标签产品线" },
  { slot: "linerless-3-1-8-x-263:related-shipping", label: "3 1/8 x 263 无底纸标签 - 推荐运输标签图", page: "3 1/8 x 263 无底纸标签", pageUrl: "/products/linerless-labels/3-1-8-x-263", aspect: "4:3", description: "相关产品：运输和仓储标签" },
  // === 其他可能用到的 6 个 ===
  { slot: "home:product-lottery-gaming-rolls", label: "首页产品-Lottery & Gaming Rolls", page: "首页", pageUrl: "/", aspect: "4:3", description: "（备用）首页彩票游戏纸卷" },
  { slot: "home:product-colored-thermal-paper", label: "首页产品-Colored Thermal Paper", page: "首页", pageUrl: "/", aspect: "4:3", description: "（备用）首页彩色热敏纸" },
  { slot: "home:product-coreless-paper-roll", label: "首页产品-Coreless Paper Roll", page: "首页", pageUrl: "/", aspect: "4:3", description: "（备用）首页无芯纸卷" },
  { slot: "home:product-multi-ply-carbonless-rolls", label: "首页产品-Multi-Ply Carbonless Rolls", page: "首页", pageUrl: "/", aspect: "4:3", description: "（备用）首页无碳复写纸卷" },
  { slot: "home:product-oem-printed-receipts", label: "首页产品-OEM Printed Receipts", page: "首页", pageUrl: "/", aspect: "4:3", description: "（备用）首页 OEM 印刷收据" },

  // 首页「完整产品线」6 类目模块（Hero 下方），admin 可单独换图
  { slot: "home:category-thermal-rolls", label: "首页类目-热敏纸卷", page: "首页", pageUrl: "/", aspect: "4:3", description: "完整产品线模块 - 热敏纸卷类目卡片" },
  { slot: "home:category-thermal-labels", label: "首页类目-热敏标签", page: "首页", pageUrl: "/", aspect: "4:3", description: "完整产品线模块 - 热敏标签类目卡片" },
  { slot: "home:category-can-labels", label: "首页类目-灌装/罐头标签", page: "首页", pageUrl: "/", aspect: "4:3", description: "完整产品线模块 - 灌装标签类目卡片" },
  { slot: "home:category-bottle-labels", label: "首页类目-瓶装标签", page: "首页", pageUrl: "/", aspect: "4:3", description: "完整产品线模块 - 瓶装标签类目卡片（原洗涤剂标签）" },
  { slot: "home:category-carbonless", label: "首页类目-无碳复写纸表格", page: "首页", pageUrl: "/", aspect: "4:3", description: "完整产品线模块 - 无碳复写纸表格类目卡片" },
  { slot: "home:category-jumbo-rolls", label: "首页类目-巨型卷代理", page: "首页", pageUrl: "/", aspect: "4:3", description: "完整产品线模块 - 巨型卷代理销售类目卡片" },
  { slot: "home:category-custom-rolls", label: "首页类目-定制纸卷/标签", page: "首页", pageUrl: "/", aspect: "4:3", description: "完整产品线模块 - 定制印刷纸卷/标签类目卡片" },

  // ===== 关于我们（来自 src/app/about/page.tsx）=====
  { slot: "about:factory-aerial", label: "关于我们 工厂航拍图", page: "关于我们", pageUrl: "/about", aspect: "16:9" },
  { slot: "about:factory-line", label: "关于我们 生产线", page: "关于我们", pageUrl: "/about", aspect: "16:9" },

  // ===== OEM 系列 =====
  { slot: "oem:hero", label: "OEM 首页 顶部图", page: "OEM 定制", pageUrl: "/oem", aspect: "16:9" },
  { slot: "oem:case-studies-hero", label: "OEM 案例 顶部图", page: "OEM 案例", pageUrl: "/oem/case-studies", aspect: "16:9" },
  { slot: "oem:custom-printing-hero", label: "OEM 定制印刷 顶部图", page: "OEM 定制印刷", pageUrl: "/oem/custom-printing", aspect: "16:9" },
  { slot: "oem:packaging-hero", label: "OEM 包装 顶部图", page: "OEM 包装", pageUrl: "/oem/packaging", aspect: "16:9" },
  { slot: "oem:design-support-hero", label: "OEM 设计支持 顶部图", page: "OEM 设计支持", pageUrl: "/oem/design-support", aspect: "16:9" },
  { slot: "oem:ip-protection-hero", label: "OEM 知识产权保护 顶部图", page: "OEM 知识产权", pageUrl: "/oem/ip-protection", aspect: "16:9" },
  { slot: "oem:quality-assurance-hero", label: "OEM 质量保证 顶部图", page: "OEM 质量保证", pageUrl: "/oem/quality-assurance", aspect: "16:9" },
  { slot: "oem:factory", label: "OEM 工厂图（中东非洲页用）", page: "OEM 定制", pageUrl: "/markets/middle-east-africa", aspect: "16:9", description: "在中东非洲市场页用作工厂展示" },

  // ===== 生产制造 =====
  { slot: "manufacturing:hero", label: "生产制造 顶部图", page: "生产制造", pageUrl: "/manufacturing", aspect: "16:9" },
  { slot: "manufacturing:facility-aerial", label: "生产制造 工厂航拍", page: "生产制造", pageUrl: "/manufacturing", aspect: "16:9" },
  { slot: "manufacturing:facility-line", label: "生产制造 生产线", page: "生产制造", pageUrl: "/manufacturing", aspect: "16:9" },
  { slot: "manufacturing:certifications-hero", label: "认证 顶部图", page: "认证证书", pageUrl: "/manufacturing/certifications", aspect: "16:9" },
  { slot: "manufacturing:equipment-hero", label: "设备 顶部图", page: "生产设备", pageUrl: "/manufacturing/equipment", aspect: "16:9" },
  { slot: "manufacturing:quality-hero", label: "质量控制 顶部图", page: "质量控制", pageUrl: "/manufacturing/quality-control", aspect: "16:9" },

  // ===== 产品 =====
  { slot: "products:hero", label: "产品总览 顶部图", page: "产品中心", pageUrl: "/products", aspect: "16:9" },
  { slot: "products:thermal-rolls", label: "产品总览 - 热敏纸卷图", page: "产品中心", pageUrl: "/products", aspect: "4:3" },
  { slot: "products:thermal-labels", label: "产品总览 - 热敏标签图", page: "产品中心", pageUrl: "/products", aspect: "4:3" },
  { slot: "products:can-labels", label: "产品总览 - 灌装包装标签图", page: "产品中心", pageUrl: "/products", aspect: "4:3" },
  { slot: "products:detergent-labels", label: "产品总览 - 瓶装及日化包装标签图", page: "产品中心", pageUrl: "/products", aspect: "4:3" },
  { slot: "products:ncr-forms", label: "产品总览 - NCR表格图", page: "产品中心", pageUrl: "/products", aspect: "4:3" },
  { slot: "receipt-paper-rolls:hero", label: "收据纸卷聚合页 顶部图", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "16:9", description: "B2B收据纸卷聚合页首屏，展示POS、收银机和终端用纸卷" },
  { slot: "receipt-paper-rolls:series:pos", label: "收据纸卷-POS收银系列", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "16:9", description: "零售、超市、收银机和标准POS收据纸卷" },
  { slot: "receipt-paper-rolls:series:mobile", label: "收据纸卷-移动支付系列", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "16:9", description: "移动POS、银行卡终端、配送和手持设备小卷径纸卷" },
  { slot: "receipt-paper-rolls:series:kiosk", label: "收据纸卷-自助终端系列", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "16:9", description: "ATM、自助机、停车、排队和票务终端纸卷" },
  { slot: "receipt-paper-rolls:series:hospitality", label: "收据纸卷-餐饮酒店系列", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "16:9", description: "餐厅前台、厨房订单和酒店服务点打印场景" },
  { slot: "receipt-paper-rolls:series:custom", label: "收据纸卷-定制印刷系列", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "16:9", description: "Logo、条款、优惠券、二维码和背印收据纸卷" },
  { slot: "receipt-paper-rolls:series:chemistry", label: "收据纸卷-化学与保存系列", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "16:9", description: "BPA-free、BPS-free、phenol-free和图像保存要求验证" },
  { slot: "receipt-paper-rolls:series:oem", label: "收据纸卷-OEM包装系列", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "16:9", description: "经销商、私牌、内包装、纸箱和复购标识控制" },
  { slot: "receipt-paper-rolls:quality", label: "收据纸卷-终端与包装质检", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "16:10", description: "宽度、卷径、纸芯、进纸、打印、切纸、长度和包装验证" },
  { slot: "receipt-paper-rolls:applications:retail", label: "收据纸卷-零售收银应用", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "4:3", description: "零售、商超和多门店POS打印场景" },
  { slot: "receipt-paper-rolls:applications:hospitality", label: "收据纸卷-餐饮酒店应用", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "4:3", description: "餐饮、酒店、前台和厨房打印场景" },
  { slot: "receipt-paper-rolls:applications:mobile", label: "收据纸卷-移动现场应用", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "4:3", description: "移动支付、配送、出租车和现场服务手持打印场景" },
  { slot: "receipt-paper-rolls:applications:kiosk", label: "收据纸卷-自助票务应用", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "4:3", description: "自助机、停车、排队和票务设备场景" },
  { slot: "receipt-paper-rolls:applications:banking", label: "收据纸卷-银行ATM应用", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "4:3", description: "银行、ATM和金融终端记录场景" },
  { slot: "receipt-paper-rolls:applications:distributor", label: "收据纸卷-批发经销应用", page: "收据纸卷", pageUrl: "/products/receipt-paper-rolls", aspect: "4:3", description: "批发、经销、私牌、多SKU内包装和纸箱管理" },
  { slot: "custom-ncr-forms:hero", label: "定制NCR表格聚合页 顶部图", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "16:9", description: "B2B定制无碳联单首屏，展示多联表格和业务记录" },
  { slot: "custom-ncr-forms:series:loose-sets", label: "定制NCR-散套与纸垫系列", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "16:9", description: "发票、订单、凭证和工单定制散套或纸垫" },
  { slot: "custom-ncr-forms:series:two-part", label: "定制NCR-二联系列", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "16:9", description: "收据、简单发票和销售单二联复制流程" },
  { slot: "custom-ncr-forms:series:three-part", label: "定制NCR-三联系列", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "16:9", description: "客户、财务和仓储或销售三联流程" },
  { slot: "custom-ncr-forms:series:multi-part", label: "定制NCR-四联及多联系列", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "16:9", description: "物流、海关、银行和机构多方审批表格" },
  { slot: "custom-ncr-forms:series:books", label: "定制NCR-收据本与发票本系列", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "16:9", description: "编号、装订、撕页和封面的收据本与发票本" },
  { slot: "custom-ncr-forms:series:delivery", label: "定制NCR-送货与物流系列", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "16:9", description: "送货单、签收、仓库收货和异常记录表格" },
  { slot: "custom-ncr-forms:series:continuous", label: "定制NCR-连续电脑表格系列", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "16:9", description: "针式打印、连续纸、折页和ERP进纸表格" },
  { slot: "custom-ncr-forms:quality", label: "定制NCR-打样与复购控制", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "16:10", description: "联数、复写、编号、装订、模切、包装和复购验证" },
  { slot: "custom-ncr-forms:applications:finance", label: "定制NCR-财务发票应用", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "4:3", description: "发票、收据、凭证和财务留档应用" },
  { slot: "custom-ncr-forms:applications:retail", label: "定制NCR-零售收据应用", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "4:3", description: "柜台、门店、销售和收据本应用" },
  { slot: "custom-ncr-forms:applications:logistics", label: "定制NCR-物流送货应用", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "4:3", description: "送货、签收、仓储和库存交接应用" },
  { slot: "custom-ncr-forms:applications:procurement", label: "定制NCR-采购审批应用", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "4:3", description: "采购订单、供应商和收货审批应用" },
  { slot: "custom-ncr-forms:applications:field-service", label: "定制NCR-现场服务应用", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "4:3", description: "维修工单、服务单和客户签字应用" },
  { slot: "custom-ncr-forms:applications:institutional", label: "定制NCR-政府机构应用", page: "定制NCR表格", pageUrl: "/products/custom-ncr-forms", aspect: "4:3", description: "许可、检查、公共采购和机构留档应用" },
  { slot: "delivery-note-forms:hero", label: "送货单聚合页 顶部图", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "16:9", description: "B2B送货单、签收、POD和仓储交接记录首屏" },
  { slot: "delivery-note-forms:series:three-part", label: "送货单-三联系列", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "16:9", description: "司机、仓库或办公室、客户三联交接记录" },
  { slot: "delivery-note-forms:series:waybill", label: "送货单-四联运单系列", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "16:9", description: "承运商、财务、分支或存档参与的四联运单" },
  { slot: "delivery-note-forms:series:pod", label: "送货单-POD签收系列", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "16:9", description: "签收人、日期、时间、货物状态和异常字段" },
  { slot: "delivery-note-forms:series:receiving", label: "送货单-仓库收货系列", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "16:9", description: "采购订单、收货数量、短缺、破损和验收记录" },
  { slot: "delivery-note-forms:series:transfer", label: "送货单-库存调拨系列", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "16:9", description: "仓库、分支、门店之间库存调拨和交接记录" },
  { slot: "delivery-note-forms:series:books", label: "送货单-编号本册系列", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "16:9", description: "编号、装订、撕页和护写封面的送货单本册" },
  { slot: "delivery-note-forms:series:continuous", label: "送货单-连续电脑表格系列", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "16:9", description: "ERP、WMS和针式打印连续送货单与装箱单" },
  { slot: "delivery-note-forms:quality", label: "送货单-打样与复购控制", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "16:10", description: "联次清晰度、异常字段、签名、编号、装订、包装和复购验证" },
  { slot: "delivery-note-forms:applications:last-mile", label: "送货单-末端配送应用", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "4:3", description: "零售补货、本地配送和客户签收应用" },
  { slot: "delivery-note-forms:applications:freight", label: "送货单-货运3PL应用", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "4:3", description: "发货人、承运商、仓库、收货人和财务多方交接" },
  { slot: "delivery-note-forms:applications:warehouse", label: "送货单-仓库收货应用", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "4:3", description: "供应商送货、收货检验、库存入账和差异处理" },
  { slot: "delivery-note-forms:applications:transfer", label: "送货单-库存调拨应用", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "4:3", description: "仓库、分支、门店和生产地点之间库存移动" },
  { slot: "delivery-note-forms:applications:field-service", label: "送货单-现场交付应用", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "4:3", description: "设备、备件、工具、安装和现场服务客户交接" },
  { slot: "delivery-note-forms:applications:port", label: "送货单-港口货运应用", page: "送货单与POD表格", pageUrl: "/products/delivery-note-forms", aspect: "4:3", description: "港口、海关、航空货运、货物放行和状态交接" },
  { slot: "continuous-computer-forms:hero", label: "连续电脑表格聚合页 顶部图", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "16:9", description: "B2B连续纸、折页、链孔和系统打印表格首屏" },
  { slot: "continuous-computer-forms:series:plain", label: "连续表格-单层白纸系列", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "16:9", description: "ERP、报表、清单和系统输出单层折页纸" },
  { slot: "continuous-computer-forms:series:carbonless", label: "连续表格-多联无碳系列", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "16:9", description: "二联、三联和四联连续无碳复写表格" },
  { slot: "continuous-computer-forms:series:preprinted", label: "连续表格-预印业务表格系列", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "16:9", description: "固定版面、表格、条款和系统可变数据区域预印" },
  { slot: "continuous-computer-forms:series:finance", label: "连续表格-发票对账系列", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "16:9", description: "发票、对账、账务记录和财务系统输出" },
  { slot: "continuous-computer-forms:series:logistics", label: "连续表格-物流仓储系列", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "16:9", description: "送货单、装箱单、运单、收货和库存移动表格" },
  { slot: "continuous-computer-forms:series:numbered", label: "连续表格-编号条码系列", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "16:9", description: "连续编号、条码、二维码和系统引用字段" },
  { slot: "continuous-computer-forms:series:oem", label: "连续表格-OEM批发系列", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "16:9", description: "经销商、商业印刷商、堆叠、内包、纸箱和托盘项目" },
  { slot: "continuous-computer-forms:quality", label: "连续表格-走纸与包装质检", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "16:10", description: "总宽、成品宽、表深、链孔、走纸、套印、复写、撕线和堆叠验证" },
  { slot: "continuous-computer-forms:applications:finance", label: "连续表格-ERP财务应用", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "4:3", description: "ERP发票、对账、账务和文件留存系统输出" },
  { slot: "continuous-computer-forms:applications:warehouse", label: "连续表格-WMS仓储应用", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "4:3", description: "拣货、装箱、收货、库存和批量打印工作站" },
  { slot: "continuous-computer-forms:applications:logistics", label: "连续表格-物流运输应用", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "4:3", description: "3PL、发运、运单、送货和多方联次表格" },
  { slot: "continuous-computer-forms:applications:manufacturing", label: "连续表格-制造管理应用", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "4:3", description: "工单、物料、发运和生产管理系统记录" },
  { slot: "continuous-computer-forms:applications:institutional", label: "连续表格-机构系统应用", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "4:3", description: "政府、公用事业和机构系统编号与存档表格" },
  { slot: "continuous-computer-forms:applications:distributor", label: "连续表格-商业印刷批发应用", page: "连续电脑表格", pageUrl: "/products/continuous-computer-forms", aspect: "4:3", description: "多SKU、白纸、预印、堆叠、纸箱和复购供应" },
  { slot: "bpa-free-thermal-paper:hero", label: "BPA-Free热敏纸聚合页 顶部图", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "16:9", description: "B2B有文件范围的BPA-Free热敏纸卷项目首屏" },
  { slot: "bpa-free-thermal-paper:series:documented", label: "BPA-Free热敏纸-文件匹配系列", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "16:9", description: "指定纸种、检测物质、报告范围和批次关联" },
  { slot: "bpa-free-thermal-paper:series:phenol-free", label: "BPA-Free热敏纸-无酚系列", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "16:9", description: "BPS-Free和Phenol-Free独立化学声明路线" },
  { slot: "bpa-free-thermal-paper:series:pos", label: "BPA-Free热敏纸-POS收银系列", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "16:9", description: "零售、超市、餐厅和标准POS收据纸卷" },
  { slot: "bpa-free-thermal-paper:series:mobile", label: "BPA-Free热敏纸-移动终端系列", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "16:9", description: "移动POS、支付、配送和手持终端小卷径纸卷" },
  { slot: "bpa-free-thermal-paper:series:custom", label: "BPA-Free热敏纸-定制印刷系列", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "16:9", description: "指定BPA-Free纸种上的Logo、条款、促销和二维码印刷" },
  { slot: "bpa-free-thermal-paper:series:retention", label: "BPA-Free热敏纸-保存期系列", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "16:9", description: "按保存期、储存和接触条件审核的纸种路线" },
  { slot: "bpa-free-thermal-paper:series:oem", label: "BPA-Free热敏纸-OEM批发系列", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "16:9", description: "经销商、私牌、多尺寸、内包、纸箱和托盘项目" },
  { slot: "bpa-free-thermal-paper:quality", label: "BPA-Free热敏纸-声明与批次审核", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "16:10", description: "检测物质、报告、纸种、试机、包装声明和复购批次关联" },
  { slot: "bpa-free-thermal-paper:applications:retail", label: "BPA-Free热敏纸-零售应用", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "4:3", description: "零售、商超、收银台和多门店补货项目" },
  { slot: "bpa-free-thermal-paper:applications:hospitality", label: "BPA-Free热敏纸-餐饮酒店应用", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "4:3", description: "餐厅、酒店、热油湿手环境和高频换纸场景" },
  { slot: "bpa-free-thermal-paper:applications:payment", label: "BPA-Free热敏纸-支付终端应用", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "4:3", description: "支付终端、移动POS和现场设备纸卷项目" },
  { slot: "bpa-free-thermal-paper:applications:banking", label: "BPA-Free热敏纸-银行ATM应用", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "4:3", description: "银行、ATM、金融终端、保存和材料文件审核" },
  { slot: "bpa-free-thermal-paper:applications:healthcare", label: "BPA-Free热敏纸-医疗机构应用", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "4:3", description: "医疗和机构采购中的更广化学范围与文件要求" },
  { slot: "bpa-free-thermal-paper:applications:distributor", label: "BPA-Free热敏纸-经销私牌应用", page: "BPA-Free热敏纸", pageUrl: "/products/bpa-free-thermal-paper", aspect: "4:3", description: "多SKU、文件、内包装、纸箱、条码和托盘供应" },
  { slot: "colored-thermal-paper:hero", label: "彩色热敏纸聚合页 顶部图", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "16:9", description: "展示彩色底纸、热敏显色和预印路线的B2B彩色热敏纸卷项目" },
  { slot: "colored-thermal-paper:series:tinted-base", label: "彩色热敏纸-彩色底纸系列", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "16:9", description: "按实物色样和打印对比度审批的彩色底纸热敏纸卷" },
  { slot: "colored-thermal-paper:series:pos", label: "彩色热敏纸-POS收据系列", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "16:9", description: "零售、商超、部门和活动编码POS彩色收据纸卷" },
  { slot: "colored-thermal-paper:series:mobile", label: "彩色热敏纸-移动终端系列", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "16:9", description: "移动POS、支付、配送和便携终端彩色小卷径纸卷" },
  { slot: "colored-thermal-paper:series:preprinted", label: "彩色热敏纸-定制预印系列", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "16:9", description: "油墨Logo、条款、促销、安全图案和色块预印路线" },
  { slot: "colored-thermal-paper:series:image-color", label: "彩色热敏纸-热敏显色系列", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "16:9", description: "按打印机能量、显色、密度和保存需求审核的热敏显色纸种" },
  { slot: "colored-thermal-paper:series:documented", label: "彩色热敏纸-文件与保存系列", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "16:9", description: "化学声明、纸种文件、保存和接触条件独立审核路线" },
  { slot: "colored-thermal-paper:series:oem", label: "彩色热敏纸-OEM多色系列", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "16:9", description: "经销商、私牌、多颜色、多尺寸、包装和复购SKU项目" },
  { slot: "colored-thermal-paper:quality", label: "彩色热敏纸-色样与批次审核", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "16:10", description: "实物色样、光源、打印对比度、扫码、批次色差和包装复购控制" },
  { slot: "colored-thermal-paper:applications:retail", label: "彩色热敏纸-零售应用", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "4:3", description: "零售、商超、部门、服务台和活动编码收据场景" },
  { slot: "colored-thermal-paper:applications:hospitality", label: "彩色热敏纸-餐饮酒店应用", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "4:3", description: "前台、厨房、服务站和订单路由彩色纸卷场景" },
  { slot: "colored-thermal-paper:applications:ticketing", label: "彩色热敏纸-票务终端应用", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "4:3", description: "票务、停车、排队、自助终端和可变数据场景" },
  { slot: "colored-thermal-paper:applications:financial", label: "彩色热敏纸-金融机构应用", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "4:3", description: "银行、支付、机构记录的可读性、保存和文件审核" },
  { slot: "colored-thermal-paper:applications:promotion", label: "彩色热敏纸-促销活动应用", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "4:3", description: "活动、促销、品牌预印和多版本彩色纸卷项目" },
  { slot: "colored-thermal-paper:applications:distributor", label: "彩色热敏纸-经销私牌应用", page: "彩色热敏纸", pageUrl: "/products/colored-thermal-paper", aspect: "4:3", description: "多颜色、多尺寸、色样、标签、纸箱和托盘批发供应" },
  { slot: "till-rolls:hero", label: "Till Rolls聚合页 顶部图", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "16:9", description: "57mm、80mm、EPOS和支付终端Till Rolls B2B项目首屏" },
  { slot: "till-rolls:series:epos", label: "Till Rolls-EPOS收银系列", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "16:9", description: "零售、商超、餐饮和标准EPOS热敏收据纸卷" },
  { slot: "till-rolls:series:80mm", label: "Till Rolls-80mm系列", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "16:9", description: "80mm零售、餐饮和台式EPOS纸卷" },
  { slot: "till-rolls:series:57mm", label: "Till Rolls-57mm系列", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "16:9", description: "57mm刷卡机、移动支付和便携终端纸卷" },
  { slot: "till-rolls:series:impact", label: "Till Rolls-普通纸多联系列", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "16:9", description: "色带或针式打印机用普通纸、双胶纸和多联纸卷" },
  { slot: "till-rolls:series:custom", label: "Till Rolls-定制印刷系列", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "16:9", description: "Logo、条款、促销、二维码和背印Till Rolls" },
  { slot: "till-rolls:series:documented", label: "Till Rolls-文件与保存系列", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "16:9", description: "化学声明、纸种文件、保存期和储存条件审核" },
  { slot: "till-rolls:series:oem", label: "Till Rolls-OEM批发系列", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "16:9", description: "经销商、私牌、多尺寸、内包、纸箱和托盘项目" },
  { slot: "till-rolls:quality", label: "Till Rolls-试机与包装审核", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "16:10", description: "尺寸、试机、打印、多联传递、保存、包装和复购控制" },
  { slot: "till-rolls:applications:retail", label: "Till Rolls-零售商超应用", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3", description: "零售、商超、多收银台和门店补货场景" },
  { slot: "till-rolls:applications:hospitality", label: "Till Rolls-餐饮酒店应用", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3", description: "餐厅、酒吧、酒店前台和厨房打印场景" },
  { slot: "till-rolls:applications:payment", label: "Till Rolls-刷卡移动终端应用", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3", description: "刷卡机、移动POS、配送和现场终端纸卷" },
  { slot: "till-rolls:applications:kiosk", label: "Till Rolls-自助票务应用", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3", description: "自助、停车、票务和专业终端纸卷" },
  { slot: "till-rolls:applications:institutional", label: "Till Rolls-金融机构应用", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3", description: "银行、医疗和机构终端记录、保存与文件审核" },
  { slot: "till-rolls:applications:distributor", label: "Till Rolls-经销私牌应用", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3", description: "多SKU、内包装、纸箱、条码、托盘和批发供应" },
  { slot: "thermal-rolls:hero", label: "热敏纸卷 详情页 顶部图", page: "热敏纸卷详情", pageUrl: "/products/thermal-paper-rolls/blank", aspect: "16:9", description: "SizeDetailPage 用，所有热敏纸卷尺寸详情页共享" },
  { slot: "thermal-roll-57x30mm:hero", label: "57x30mm 热敏纸卷 - 主图", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/57x30mm", aspect: "16:9", description: "57x30mm 产品卷材与包装参考" },
  { slot: "thermal-roll-57x40mm:hero", label: "57x40mm 热敏纸卷 - 主图", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/57x40mm", aspect: "16:9", description: "57x40mm 产品卷材与包装参考" },
  { slot: "thermal-roll-57x50mm:hero", label: "57x50mm 热敏纸卷 - 主图", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/57x50mm", aspect: "16:9", description: "57x50mm 产品卷材与包装参考" },
  { slot: "thermal-roll-80x70mm:hero", label: "80x70mm 热敏纸卷 - 主图", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/80x70mm", aspect: "16:9", description: "80x70mm 产品卷材与包装参考" },
  { slot: "thermal-roll-80x80mm:hero", label: "80x80mm 热敏纸卷 - 主图", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/80x80mm", aspect: "16:9", description: "80x80mm 产品卷材与包装参考" },
  { slot: "thermal-roll-110x80mm:hero", label: "110x80mm 热敏纸卷 - 主图", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/110x80mm", aspect: "16:9", description: "110x80mm 产品卷材与包装参考" },
  { slot: "thermal-rolls:detail-application", label: "热敏纸卷详情 - 应用场景", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/80x80mm", aspect: "4:3", description: "用于确认纸卷规格的 POS、移动打印或收据场景" },
  { slot: "thermal-rolls:detail-quality", label: "热敏纸卷详情 - 质量控制", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/80x80mm", aspect: "4:3", description: "热敏纸卷生产和质量控制参考" },
  { slot: "thermal-rolls:detail-risk", label: "热敏纸卷详情 - 采购风险", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/80x80mm", aspect: "4:3", description: "用于说明打印机、长度和储存风险的收据场景" },
  { slot: "thermal-rolls:detail-specification", label: "热敏纸卷详情 - 规格审核", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/80x80mm", aspect: "4:3", description: "纸卷宽度、卷径、纸芯和包装规格审核" },
  { slot: "thermal-rolls:detail-workflow", label: "热敏纸卷详情 - 审批流程", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/80x80mm", aspect: "4:3", description: "样品、生产与复购审批流程" },
  { slot: "thermal-rolls:detail-faq", label: "热敏纸卷详情 - FAQ 包装", page: "热敏纸卷尺寸详情", pageUrl: "/products/thermal-rolls/80x80mm", aspect: "4:3", description: "采购 FAQ 旁的出口纸箱与托盘参考" },
  { slot: "thermal-labels:hero", label: "热敏标签 详情页 顶部图", page: "热敏标签详情", pageUrl: "/products/thermal-labels/blank", aspect: "16:9", description: "SizeDetailPage 用，所有热敏标签尺寸详情页共享" },
  { slot: "shipping-labels:hero", label: "运输标签-顶部主图", page: "运输标签", pageUrl: "/products/shipping-labels", aspect: "16:9", description: "3PL与海外仓采购首屏，展示4x6卷装或折叠装运输标签" },
  { slot: "shipping-labels:overview", label: "运输标签-产品定义图", page: "运输标签", pageUrl: "/products/shipping-labels", aspect: "4:3", description: "直热式运输标签定义和报价资料模块" },
  { slot: "shipping-labels:failure-risks", label: "运输标签-运营风险图", page: "运输标签", pageUrl: "/products/shipping-labels", aspect: "4:3", description: "扫码、卡纸、脱胶和换卷风险模块" },
  { slot: "shipping-labels:rolls", label: "运输标签-卷装图", page: "运输标签", pageUrl: "/products/shipping-labels", aspect: "4:3", description: "卷装标签和桌面或工业打印机方案" },
  { slot: "shipping-labels:fanfold", label: "运输标签-折叠装图", page: "运输标签", pageUrl: "/products/shipping-labels", aspect: "4:3", description: "Z折叠连续供纸和高吞吐包装台方案" },
  { slot: "shipping-labels:applications", label: "运输标签-履约场景图", page: "运输标签", pageUrl: "/products/shipping-labels", aspect: "4:3", description: "3PL、海外仓、电商履约和快递分拨场景" },
  { slot: "shipping-labels:quality-control", label: "运输标签-质量控制图", page: "运输标签", pageUrl: "/products/shipping-labels", aspect: "4:3", description: "条码、模切、粘胶、卷绕和数量检查" },
  { slot: "shipping-labels:packing", label: "运输标签-出口包装图", page: "运输标签", pageUrl: "/products/shipping-labels", aspect: "4:3", description: "纸箱、托盘、批次标签和补货SKU控制" },
  { slot: "can-labels:hero", label: "灌装线机贴卷标 顶部图", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "16:9" },
  { slot: "can-labels:series:wraparound", label: "产品系列-环绕卷标", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "16:9", description: "圆瓶、圆罐和圆柱容器环绕贴标应用图" },
  { slot: "can-labels:series:front-back", label: "产品系列-前后标组合", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "16:9", description: "前标与背标双贴标头或组合贴标应用图" },
  { slot: "can-labels:series:clear-film", label: "产品系列-透明膜机贴标", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "16:9", description: "透明瓶、玻璃瓶和传感器识别应用图" },
  { slot: "can-labels:series:multi-sku", label: "产品系列-多SKU短版卷标", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "16:9", description: "多口味、多语言或多版本卷标分卷与箱唛管理图" },
  { slot: "product-labels:hero", label: "产品与包装标签 顶部图", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "16:9", description: "B2B产品标签聚合页首屏，展示印刷标签和实际包装" },
  { slot: "product-labels:series:custom", label: "产品标签-定制印刷系列", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "16:9", description: "品牌、产品信息和多SKU定制印刷标签系列" },
  { slot: "product-labels:series:retail", label: "产品标签-零售价签系列", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "16:9", description: "价格、货架和促销标签系列" },
  { slot: "product-labels:series:packaging", label: "产品标签-包装标签系列", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "16:9", description: "纸盒、袋、罐和产品包装标签系列" },
  { slot: "product-labels:series:food-scale", label: "产品标签-食品称重系列", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "16:9", description: "食品、熟食和称重打印标签系列" },
  { slot: "product-labels:series:barcode", label: "产品标签-条码变量系列", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "16:9", description: "SKU、UPC、二维码、批次和序列号标签系列" },
  { slot: "product-labels:series:blank", label: "产品标签-空白打印系列", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "16:9", description: "卷装、折叠和张页空白产品标签系列" },
  { slot: "product-labels:series:durable", label: "产品标签-耐用纸膜系列", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "16:9", description: "按环境条件验证的纸类和膜类耐用标签系列" },
  { slot: "product-labels:quality", label: "产品标签-验证与质量控制", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "16:10", description: "打印、扫描、模切、贴附和复购控制验证" },
  { slot: "custom-printed-labels:hero", label: "定制印刷热敏标签 顶部图", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "16:9", description: "B2B定制印刷标签聚合页首屏，展示预印刷卷标和后续变量打印区域" },
  { slot: "custom-printed-labels:series:direct-thermal", label: "定制印刷标签-直热预印系列", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "16:9", description: "带静态印刷和变量数据打印区域的直热标签" },
  { slot: "custom-printed-labels:series:thermal-transfer", label: "定制印刷标签-热转印系列", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "16:9", description: "与碳带和后续热转印流程匹配的预印刷标签" },
  { slot: "custom-printed-labels:series:product", label: "定制印刷标签-产品包装系列", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "16:9", description: "品牌、产品信息和多语言包装标签" },
  { slot: "custom-printed-labels:series:shipping", label: "定制印刷标签-品牌运输系列", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "16:9", description: "预印品牌元素并保留路由数据区域的运输标签" },
  { slot: "custom-printed-labels:series:barcode-variable", label: "定制印刷标签-条码变量系列", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "16:9", description: "静态印刷与SKU、条码、日期、批次变量数据组合" },
  { slot: "custom-printed-labels:series:machine-ready", label: "定制印刷标签-自动贴标卷标系列", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "16:9", description: "按自动或半自动贴标设备确认卷向、间距和卷材结构" },
  { slot: "custom-printed-labels:series:oem", label: "定制印刷标签-OEM多SKU系列", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "16:9", description: "多SKU、私牌包装、分卷和箱唛控制" },
  { slot: "custom-printed-labels:quality", label: "定制印刷标签-打样与复购控制", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "16:10", description: "稿件、颜色、后续打印、扫描、模切、贴附和复购验证" },
  { slot: "custom-printed-labels:applications:ecommerce", label: "定制印刷标签-电商运输应用", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "4:3", description: "电商包装台、品牌运输和退货标签场景" },
  { slot: "custom-printed-labels:applications:retail", label: "定制印刷标签-零售产品应用", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "4:3", description: "零售产品、价格、促销和包装标签场景" },
  { slot: "custom-printed-labels:applications:warehouse", label: "定制印刷标签-仓储纸箱应用", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "4:3", description: "仓库、库存、纸箱和变量路由数据场景" },
  { slot: "custom-printed-labels:applications:food", label: "定制印刷标签-食品日期应用", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "4:3", description: "食品、称重、日期、批次和追溯字段场景" },
  { slot: "custom-printed-labels:applications:filling-line", label: "定制印刷标签-灌装贴标线应用", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "4:3", description: "自动灌装、包装和贴标设备应用场景" },
  { slot: "custom-printed-labels:applications:oem", label: "定制印刷标签-OEM渠道应用", page: "定制印刷热敏标签", pageUrl: "/products/custom-printed-thermal-labels", aspect: "4:3", description: "经销商、OEM、私牌和多版本包装管理场景" },
  { slot: "detergent-labels:hero", label: "洗涤剂标签 顶部图", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "16:9" },
  { slot: "detergent-labels:series:custom", label: "洗涤剂标签-定制印刷系列", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "16:9", description: "定制印刷洗涤剂与家居清洁产品标签系列" },
  { slot: "detergent-labels:series:laundry", label: "洗涤剂标签-洗衣与织物护理系列", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "16:9", description: "洗衣液、柔顺剂和织物护理瓶贴系列" },
  { slot: "detergent-labels:series:dishwashing", label: "洗涤剂标签-洗碗与厨房清洁系列", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "16:9", description: "洗洁精、洗碗产品和厨房清洁瓶贴系列" },
  { slot: "detergent-labels:series:household", label: "洗涤剂标签-家居清洁系列", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "16:9", description: "多功能清洁剂、消毒剂和喷雾瓶贴系列" },
  { slot: "detergent-labels:series:personal-care", label: "洗涤剂标签-洗手液与个护瓶贴系列", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "16:9", description: "洗手液、沐浴露和洗护瓶贴相邻应用系列" },
  { slot: "detergent-labels:series:industrial", label: "洗涤剂标签-工业清洁与化学品系列", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "16:9", description: "工业清洁剂和化学品容器标识标签系列" },
  { slot: "detergent-labels:series:blank-variable", label: "洗涤剂标签-空白与变量数据系列", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "16:9", description: "空白、预印刷和变量数据瓶贴供应路线" },
  { slot: "ncr-forms:hero", label: "NCR无碳联单 顶部图", page: "NCR表格", pageUrl: "/products/ncr-forms", aspect: "16:9" },
  { slot: "ncr-forms:overview", label: "NCR无碳联单 产品概览图", page: "NCR表格", pageUrl: "/products/ncr-forms", aspect: "4:3", description: "NCR 是什么与报价资料模块" },
  { slot: "ncr-forms:books", label: "NCR收据本和发票本图", page: "NCR表格", pageUrl: "/products/ncr-forms", aspect: "4:3", description: "成品形式 - 收据本与发票本" },
  { slot: "ncr-forms:continuous", label: "NCR连续电脑表格图", page: "NCR表格", pageUrl: "/products/ncr-forms", aspect: "4:3", description: "成品形式 - 连续电脑表格" },
  { slot: "ncr-forms:delivery", label: "NCR送货单和运单场景图", page: "NCR表格", pageUrl: "/products/ncr-forms", aspect: "4:3", description: "成品形式 - 送货单、运单和物流表格" },
  { slot: "ncr-forms:production", label: "NCR生产与质检图", page: "NCR表格", pageUrl: "/products/ncr-forms", aspect: "4:3", description: "材料结构、生产和质检模块" },
  { slot: "ncr-receipt-books:hero", label: "NCR收据本-顶部主图", page: "NCR收据本", pageUrl: "/products/ncr-receipt-books", aspect: "16:9", description: "渠道采购首屏，展示成品收据本或真实开单场景" },
  { slot: "ncr-receipt-books:overview", label: "NCR收据本-产品定义图", page: "NCR收据本", pageUrl: "/products/ncr-receipt-books", aspect: "1:1", description: "What Are NCR Receipt Books 定义与报价清单模块" },
  { slot: "ncr-receipt-books:buyer-risk", label: "NCR收据本-采购风险图", page: "NCR收据本", pageUrl: "/products/ncr-receipt-books", aspect: "4:3", description: "复写清晰度、编号、装订和复购一致性风险模块" },
  { slot: "ncr-receipt-books:2-part", label: "NCR收据本-二联本图", page: "NCR收据本", pageUrl: "/products/ncr-receipt-books", aspect: "4:3", description: "Duplicate 2-part receipt book 产品方案" },
  { slot: "ncr-receipt-books:3-part", label: "NCR收据本-三联本图", page: "NCR收据本", pageUrl: "/products/ncr-receipt-books", aspect: "4:3", description: "Triplicate 3-part receipt book 产品方案" },
  { slot: "ncr-receipt-books:private-label", label: "NCR收据本-定制品牌图", page: "NCR收据本", pageUrl: "/products/ncr-receipt-books", aspect: "4:3", description: "定制封面、品牌字段和经销商 SKU 方案" },
  { slot: "ncr-receipt-books:production", label: "NCR收据本-生产质检图", page: "NCR收据本", pageUrl: "/products/ncr-receipt-books", aspect: "4:3", description: "材料层、编号连续性、打孔和本数质检模块" },
  { slot: "ncr-receipt-books:packing", label: "NCR收据本-私牌包装图", page: "NCR收据本", pageUrl: "/products/ncr-receipt-books", aspect: "4:3", description: "书本标签、收缩包装、内箱和出口外箱模块" },
  { slot: "ncr-invoice-books:hero", label: "NCR发票本-顶部主图", page: "NCR发票本", pageUrl: "/products/ncr-invoice-books", aspect: "16:9", description: "渠道采购首屏，展示成品发票本或真实开单场景" },
  { slot: "ncr-invoice-books:overview", label: "NCR发票本-产品定义图", page: "NCR发票本", pageUrl: "/products/ncr-invoice-books", aspect: "4:3", description: "What Is an NCR Invoice Book 定义与报价资料模块" },
  { slot: "ncr-invoice-books:buyer-risk", label: "NCR发票本-采购风险图", page: "NCR发票本", pageUrl: "/products/ncr-invoice-books", aspect: "4:3", description: "复写清晰度、编号、撕线、装订和复购一致性模块" },
  { slot: "ncr-invoice-books:2-part", label: "NCR发票本-二联本图", page: "NCR发票本", pageUrl: "/products/ncr-invoice-books", aspect: "4:3", description: "Duplicate 2-part invoice book 产品方案" },
  { slot: "ncr-invoice-books:3-part", label: "NCR发票本-三联本图", page: "NCR发票本", pageUrl: "/products/ncr-invoice-books", aspect: "4:3", description: "Triplicate 3-part invoice book 产品方案" },
  { slot: "ncr-invoice-books:private-label", label: "NCR发票本-定制品牌图", page: "NCR发票本", pageUrl: "/products/ncr-invoice-books", aspect: "4:3", description: "定制封面、品牌字段、书本标签和经销商 SKU 方案" },
  { slot: "ncr-invoice-books:production", label: "NCR发票本-生产质检图", page: "NCR发票本", pageUrl: "/products/ncr-invoice-books", aspect: "4:3", description: "复写测试、编号连续性、撕线、装订和本数质检模块" },
  { slot: "ncr-invoice-books:packing", label: "NCR发票本-私牌包装图", page: "NCR发票本", pageUrl: "/products/ncr-invoice-books", aspect: "4:3", description: "书本标签、收缩包装、内箱和出口外箱模块" },
  { slot: "ncr-applications:government-ncr-forms:hero", label: "NCR应用页-Government 顶部图", page: "NCR应用页", pageUrl: "/products/government-ncr-forms", aspect: "16:9", description: "Government NCR Forms 应用页 Hero 图" },
  { slot: "ncr-applications:port-customs-air-cargo-ncr-forms:hero", label: "NCR应用页-港口海关空运 顶部图", page: "NCR应用页", pageUrl: "/products/port-customs-air-cargo-ncr-forms", aspect: "16:9", description: "Port, Customs & Air Cargo NCR Forms 应用页 Hero 图" },
  { slot: "ncr-applications:field-service-ncr-forms:hero", label: "NCR应用页-现场服务 顶部图", page: "NCR应用页", pageUrl: "/products/field-service-ncr-forms", aspect: "16:9", description: "Field Service NCR Forms 应用页 Hero 图" },
  { slot: "ncr-applications:auto-repair-ncr-forms:hero", label: "NCR应用页-汽修车检 顶部图", page: "NCR应用页", pageUrl: "/products/auto-repair-ncr-forms", aspect: "16:9", description: "Auto Repair NCR Forms 应用页 Hero 图" },
  { slot: "auto-repair-ncr-forms:inspection", label: "汽修NCR-车辆检查场景图", page: "汽修NCR表格", pageUrl: "/products/auto-repair-ncr-forms", aspect: "4:3", description: "客户问题与车辆接车检查模块" },
  { slot: "auto-repair-ncr-forms:repair-order", label: "汽修NCR-维修工单图", page: "汽修NCR表格", pageUrl: "/products/auto-repair-ncr-forms", aspect: "4:3", description: "维修工单和估价表模块" },
  { slot: "auto-repair-ncr-forms:damage-report", label: "汽修NCR-车况与损伤记录图", page: "汽修NCR表格", pageUrl: "/products/auto-repair-ncr-forms", aspect: "4:3", description: "车辆检查和损伤报告模块" },
  { slot: "auto-repair-ncr-forms:authorization", label: "汽修NCR-维修授权表图", page: "汽修NCR表格", pageUrl: "/products/auto-repair-ncr-forms", aspect: "4:3", description: "估价和维修授权模块" },
  { slot: "auto-repair-ncr-forms:invoice", label: "汽修NCR-发票收据本图", page: "汽修NCR表格", pageUrl: "/products/auto-repair-ncr-forms", aspect: "4:3", description: "维修发票和收据本模块" },
  { slot: "auto-repair-ncr-forms:production", label: "汽修NCR-生产质检图", page: "汽修NCR表格", pageUrl: "/products/auto-repair-ncr-forms", aspect: "4:3", description: "生产、编号、复购规格和质检模块" },
  { slot: "ncr-applications:logistics-warehouse-ncr-forms:hero", label: "NCR应用页-物流仓储 顶部图", page: "NCR应用页", pageUrl: "/products/logistics-warehouse-ncr-forms", aspect: "16:9", description: "Logistics & Warehouse NCR Forms 应用页 Hero 图" },
  { slot: "ncr-applications:medical-pharmacy-ncr-forms:hero", label: "NCR应用页-医疗药房 顶部图", page: "NCR应用页", pageUrl: "/products/medical-pharmacy-ncr-forms", aspect: "16:9", description: "Medical & Pharmacy NCR Forms 应用页 Hero 图" },

  // 热敏标签 - 应用场景图（在 label-sizes-data.tsx 中用 slotKey 引用）
  { slot: "thermal-labels:applications:ecommerce", label: "热敏标签-电商物流", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "E-commerce / 4x6 主流电商发货标签场景" },
  { slot: "thermal-labels:applications:amazon", label: "热敏标签-亚马逊 FBA", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "Amazon FBA 仓储发货标签场景" },
  { slot: "thermal-labels:applications:shipping", label: "热敏标签-国际快递", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "UPS/FedEx/DHL/DPD 国际快递面单场景" },
  { slot: "thermal-labels:applications:logistics", label: "热敏标签-物流配送", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "USPS/Hermes/Evri 配送面单场景" },
  { slot: "thermal-labels:applications:warehouse", label: "热敏标签-仓库管理", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "仓库 WMS 系统打印标签场景" },
  { slot: "thermal-labels:applications:crossborder", label: "热敏标签-跨境贸易", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "跨境电商/海关合规标签场景" },
  { slot: "thermal-labels:applications:barcode", label: "热敏标签-条码打印", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "条码/2D 码扫描标签场景" },
  { slot: "thermal-labels:applications:inventory", label: "热敏标签-库存盘点", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "库存/资产盘点标签场景" },
  { slot: "thermal-labels:applications:retail", label: "热敏标签-零售货架", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "零售价签/货架标签场景" },
  { slot: "thermal-labels:applications:product", label: "热敏标签-产品标识", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "SKU/产品 ID 标签场景" },
  { slot: "thermal-labels:applications:asset", label: "热敏标签-资产追踪", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "IT 资产/设备追踪标签场景" },
  { slot: "thermal-labels:applications:packaging", label: "热敏标签-产品包装", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "零售包装大标签场景" },
  { slot: "thermal-labels:applications:food", label: "热敏标签-食品标签", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "食品安全/日期标签场景" },
  { slot: "thermal-labels:applications:pharmacy", label: "热敏标签-药品标签", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "处方药/非处方药标签场景" },
  { slot: "thermal-labels:applications:europe", label: "热敏标签-欧洲电商", page: "热敏标签", pageUrl: "/products/thermal-labels", aspect: "4:3", description: "A6 欧洲电商标签场景" },
  { slot: "product-labels:applications:retail", label: "产品标签-零售价格与货架应用", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "4:3", description: "商超价格、促销和货架运营标签场景" },
  { slot: "product-labels:applications:food", label: "产品标签-食品与称重应用", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "4:3", description: "食品、熟食、烘焙和称重包装标签场景" },
  { slot: "product-labels:applications:personal-care", label: "产品标签-个护化妆品应用", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "4:3", description: "化妆品、个护和洗护产品包装标签场景" },
  { slot: "product-labels:applications:household", label: "产品标签-家居清洁应用", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "4:3", description: "洗涤剂、清洁剂和家居产品容器标签场景" },
  { slot: "product-labels:applications:industrial", label: "产品标签-工业标识应用", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "4:3", description: "零部件、料箱和工业产品识别标签场景" },
  { slot: "product-labels:applications:oem", label: "产品标签-OEM多SKU应用", page: "产品与包装标签", pageUrl: "/products/product-labels", aspect: "4:3", description: "OEM、私牌和多SKU标签分卷装箱管理场景" },
  { slot: "barcode-labels:hero", label: "条码标签 顶部图", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "16:9", description: "B2B条码标签聚合页首屏，展示卷装条码标签和扫描工作流" },
  { slot: "barcode-labels:series:custom-variable", label: "条码标签-定制变量数据系列", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "16:9", description: "SKU、UPC、EAN、FNSKU、二维码、批次和序列号标签系列" },
  { slot: "barcode-labels:series:sku-retail", label: "条码标签-零售SKU系列", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "16:9", description: "零售SKU、UPC、价格和货架条码标签系列" },
  { slot: "barcode-labels:series:warehouse", label: "条码标签-仓库库存系列", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "16:9", description: "仓库货位、库存、拣选和盘点标签系列" },
  { slot: "barcode-labels:series:fnsku", label: "条码标签-FNSKU平台系列", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "16:9", description: "电商平台FNSKU和商品准备标签系列" },
  { slot: "barcode-labels:series:carton-pallet", label: "条码标签-纸箱托盘系列", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "16:9", description: "纸箱、外箱、托盘和物流交接条码标签系列" },
  { slot: "barcode-labels:series:asset", label: "条码标签-资产零部件系列", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "16:9", description: "资产、设备、零部件和序列号标签系列" },
  { slot: "barcode-labels:series:cold-durable", label: "条码标签-冷链耐用系列", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "16:9", description: "低温、冷凝、油污和耐磨条件条码标签系列" },
  { slot: "barcode-labels:quality", label: "条码标签-打印扫描质量控制", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "16:10", description: "数据、打印、贴附、扫描和复购控制验证" },
  { slot: "barcode-labels:applications:retail", label: "条码标签-零售扫描应用", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "4:3", description: "零售SKU、价格、货架和POS扫描场景" },
  { slot: "barcode-labels:applications:marketplace", label: "条码标签-平台FNSKU应用", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "4:3", description: "电商平台商品准备和FNSKU贴标场景" },
  { slot: "barcode-labels:applications:warehouse", label: "条码标签-仓库应用", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "4:3", description: "仓库收货、上架、货位、拣选和盘点场景" },
  { slot: "barcode-labels:applications:pallet", label: "条码标签-托盘物流应用", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "4:3", description: "纸箱、托盘、路由和物流交接扫描场景" },
  { slot: "barcode-labels:applications:manufacturing", label: "条码标签-制造追溯应用", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "4:3", description: "制造零部件、工序、资产和序列追溯场景" },
  { slot: "barcode-labels:applications:cold-chain", label: "条码标签-冷链应用", page: "条码标签", pageUrl: "/products/barcode-labels", aspect: "4:3", description: "食品、医药和冷链包装条码扫描场景" },

  // 热敏纸卷 - 应用场景图（在 roll-sizes-data.tsx 中用 slotKey 引用）
  { slot: "thermal-rolls:applications:pos", label: "热敏纸卷-POS 收银", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "POS 收银机收据打印场景" },
  { slot: "thermal-rolls:applications:restaurant", label: "热敏纸卷-餐厅打印", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "餐厅厨房/前台小票场景" },
  { slot: "thermal-rolls:applications:retail", label: "热敏纸卷-零售结账", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "零售门店结账小票场景" },
  { slot: "thermal-rolls:applications:supermarket", label: "热敏纸卷-超市收银", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "超市大批量收银小票场景" },
  { slot: "thermal-rolls:applications:hotel", label: "热敏纸卷-酒店前台", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "酒店前台账单/收据场景" },
  { slot: "thermal-rolls:applications:taxi", label: "热敏纸卷-出租车计价器", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "出租车计价器小票场景" },
  { slot: "thermal-rolls:applications:parking", label: "热敏纸卷-停车收费", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "停车场自助收费机小票场景" },
  { slot: "thermal-rolls:applications:mobile", label: "热敏纸卷-移动支付终端", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "mPOS/Square/Clover 移动支付小票场景" },
  { slot: "thermal-rolls:applications:handheld", label: "热敏纸卷-手持打印机", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "现场服务/配送手持打印机场景" },
  { slot: "thermal-rolls:applications:lottery", label: "热敏纸卷-彩票/游戏", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "彩票/游戏终端票据场景" },
  { slot: "thermal-rolls:applications:hospitality", label: "热敏纸卷-酒店服务", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "酒店宾客服务结算场景" },
  { slot: "thermal-rolls:applications:kiosk", label: "热敏纸卷-自助终端", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "自助点单/购票终端场景" },
  { slot: "thermal-rolls:applications:credit-card", label: "热敏纸卷-信用卡终端", page: "热敏纸卷", pageUrl: "/products/thermal-rolls", aspect: "4:3", description: "信用卡支付终端小票场景" },

  // 罐头标签 - 应用场景图（在 can-labels-data.tsx 中用 slotKey 引用）
  { slot: "can-labels:applications:beverage", label: "灌装线卷标-饮料线", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "饮料瓶灌装和自动贴标生产线应用图" },
  { slot: "can-labels:applications:food", label: "灌装线卷标-食品线", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "食品、酱料和罐装容器自动贴标应用图" },
  { slot: "can-labels:applications:canning", label: "灌装线卷标-代工多SKU", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "Co-packer 和多 SKU 灌装贴标线应用图" },
  { slot: "can-labels:applications:retail", label: "罐头标签-零售货架", page: "罐头标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "超市货架陈列应用图" },
  { slot: "can-labels:applications:pet-food", label: "灌装线卷标-个护产品", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "洗护、化妆品和小直径容器自动贴标应用图" },
  { slot: "can-labels:applications:industrial", label: "灌装线卷标-工业液体", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "润滑油、化学品和工业液体灌装贴标应用图" },
  { slot: "can-labels:applications:chemical", label: "罐头标签-化工品", page: "罐头标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "GHS 化工品罐应用图" },
  { slot: "can-labels:applications:paint", label: "灌装线卷标-家居日化", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "清洁剂、洗涤剂和家居日化灌装贴标应用图" },
  { slot: "can-labels:applications:seafood", label: "罐头标签-海产品", page: "罐头标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "金枪鱼/沙丁鱼等海产罐应用图" },
  { slot: "can-labels:applications:vegetable", label: "罐头标签-蔬菜", page: "罐头标签", pageUrl: "/products/can-labels", aspect: "4:3", description: "蔬菜/番茄/豆类罐应用图" },

  // 洗涤剂标签 - 应用场景图（在 detergent-labels-data.tsx 中用 slotKey 引用）
  { slot: "detergent-labels:applications:laundry", label: "洗涤标签-洗衣液", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "洗衣液/洗衣粉应用图" },
  { slot: "detergent-labels:applications:dishwash", label: "洗涤标签-洗碗液", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "洗洁精/洗碗液应用图" },
  { slot: "detergent-labels:applications:cleaner", label: "洗涤标签-清洁剂", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "多功能清洁剂/漂白剂/地板清洁剂应用图" },
  { slot: "detergent-labels:applications:handsoap", label: "洗涤标签-洗手液", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "洗手液/泡沫洗手应用图" },
  { slot: "detergent-labels:applications:industrial", label: "洗涤标签-工业清洁", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "工业级清洁产品应用图" },
  { slot: "detergent-labels:applications:retail", label: "洗涤标签-零售陈列", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "超市货架/私品牌陈列应用图" },
  { slot: "detergent-labels:applications:fabric", label: "洗涤标签-织物护理", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "柔顺剂/去渍剂应用图" },
  { slot: "detergent-labels:applications:bathroom", label: "洗涤标签-浴室清洁", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "浴室/瓷砖清洁喷雾应用图" },
  { slot: "detergent-labels:applications:kitchen", label: "洗涤标签-厨房清洁", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "厨房去油/表面清洁应用图" },
  { slot: "detergent-labels:applications:hotel", label: "洗涤标签-酒店用品", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "酒店/酒店配套清洁用品应用图" },
  { slot: "detergent-labels:applications:pet", label: "洗涤标签-PET透明瓶", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "PET和透明硬质瓶标签适配场景" },
  { slot: "detergent-labels:applications:spray", label: "洗涤标签-喷雾触发瓶", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "浴室、厨房和消毒剂触发喷雾瓶场景" },
  { slot: "detergent-labels:applications:refill", label: "洗涤标签-补充装软包装", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "补充装袋和软包装标签应用场景" },
  { slot: "detergent-labels:applications:filling-line", label: "洗涤标签-自动灌装贴标线", page: "洗涤剂标签", pageUrl: "/products/detergent-labels", aspect: "4:3", description: "家居清洁产品自动灌装与贴标线场景" },
  { slot: "thermal-labels:blank-hero", label: "热敏标签 空白 顶部图", page: "热敏空白标签", pageUrl: "/products/thermal-labels/blank", aspect: "16:9" },
  { slot: "thermal-labels:custom-hero", label: "热敏标签 定制 顶部图", page: "热敏定制标签", pageUrl: "/products/thermal-labels/custom-printed", aspect: "16:9" },
  { slot: "thermal-paper-rolls:blank-hero", label: "热敏纸卷 空白 顶部图", page: "热敏空白纸卷", pageUrl: "/products/thermal-paper-rolls/blank", aspect: "16:9" },
  { slot: "thermal-paper-rolls:custom-hero", label: "热敏纸卷 定制 顶部图", page: "热敏定制纸卷", pageUrl: "/products/thermal-paper-rolls/custom-printed", aspect: "16:9" },
  { slot: "can-labels:blank-hero", label: "空白机贴卷筒标签", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "16:9" },
  { slot: "can-labels:custom-hero", label: "定制印刷机贴卷筒标签", page: "灌装线自动贴标卷筒标签", pageUrl: "/products/can-labels", aspect: "16:9" },
  { slot: "detergent-labels:blank-hero", label: "洗涤剂标签 空白 顶部图", page: "洗涤空白标签", pageUrl: "/products/detergent-labels/blank", aspect: "16:9" },
  { slot: "detergent-labels:custom-hero", label: "洗涤剂标签 定制 顶部图", page: "洗涤定制标签", pageUrl: "/products/detergent-labels/custom-printed", aspect: "16:9" },

  // ===== 市场页面 =====
  { slot: "markets:africa-hero", label: "非洲市场 顶部图", page: "非洲市场", pageUrl: "/markets/africa", aspect: "16:9" },
  { slot: "markets:southeast-asia-hero", label: "东南亚市场 顶部图", page: "东南亚市场", pageUrl: "/markets/southeast-asia", aspect: "16:9" },
  { slot: "markets:middle-east-hero", label: "中东市场 顶部图", page: "中东市场", pageUrl: "/markets/middle-east", aspect: "16:9" },
  { slot: "markets:middle-east-africa-hero", label: "中东非洲 顶部图", page: "中东非洲市场", pageUrl: "/markets/middle-east-africa", aspect: "16:9" },
  { slot: "markets:europe-hero", label: "欧洲市场 顶部图", page: "欧洲市场", pageUrl: "/markets/europe", aspect: "16:9" },
  // 各国子页面 hero
  { slot: "markets:ghana-hero", label: "加纳 顶部图", page: "加纳市场", pageUrl: "/markets/africa/ghana", aspect: "16:9" },
  { slot: "markets:kenya-hero", label: "肯尼亚 顶部图", page: "肯尼亚市场", pageUrl: "/markets/africa/kenya", aspect: "16:9" },
  { slot: "markets:nigeria-hero", label: "尼日利亚 顶部图", page: "尼日利亚市场", pageUrl: "/markets/africa/nigeria", aspect: "16:9" },
  { slot: "markets:ethiopia-hero", label: "埃塞俄比亚 顶部图", page: "埃塞俄比亚市场", pageUrl: "/markets/africa/ethiopia", aspect: "16:9" },
  { slot: "markets:south-africa-hero", label: "南非 顶部图", page: "南非市场", pageUrl: "/markets/africa/south-africa", aspect: "16:9" },
  { slot: "markets:tanzania-hero", label: "坦桑尼亚 顶部图", page: "坦桑尼亚市场", pageUrl: "/markets/africa/tanzania", aspect: "16:9" },
  { slot: "markets:egypt-hero", label: "埃及 顶部图", page: "埃及市场", pageUrl: "/markets/middle-east/egypt", aspect: "16:9" },
  { slot: "markets:saudi-arabia-hero", label: "沙特 顶部图", page: "沙特市场", pageUrl: "/markets/middle-east/saudi-arabia", aspect: "16:9" },
  { slot: "markets:turkey-hero", label: "土耳其 顶部图", page: "土耳其市场", pageUrl: "/markets/middle-east/turkey", aspect: "16:9" },
  { slot: "markets:uae-hero", label: "阿联酋 顶部图", page: "阿联酋市场", pageUrl: "/markets/middle-east/uae", aspect: "16:9" },
  { slot: "markets:italy-hero", label: "意大利 顶部图", page: "意大利市场", pageUrl: "/markets/europe/italy", aspect: "16:9" },
  { slot: "markets:indonesia-hero", label: "印尼 顶部图", page: "印尼市场", pageUrl: "/markets/southeast-asia/indonesia", aspect: "16:9" },
  { slot: "markets:malaysia-hero", label: "马来西亚 顶部图", page: "马来西亚市场", pageUrl: "/markets/southeast-asia/malaysia", aspect: "16:9" },
  { slot: "markets:philippines-hero", label: "菲律宾 顶部图", page: "菲律宾市场", pageUrl: "/markets/southeast-asia/philippines", aspect: "16:9" },
  { slot: "markets:singapore-hero", label: "新加坡 顶部图", page: "新加坡市场", pageUrl: "/markets/southeast-asia/singapore", aspect: "16:9" },
  { slot: "markets:thailand-hero", label: "泰国 顶部图", page: "泰国市场", pageUrl: "/markets/southeast-asia/thailand", aspect: "16:9" },
  { slot: "markets:vietnam-hero", label: "越南 顶部图", page: "越南市场", pageUrl: "/markets/southeast-asia/vietnam", aspect: "16:9" },

  // ===== 资源中心 =====
  { slot: "resources:application-cases-retail-pos", label: "应用案例 - 零售 POS", page: "应用案例", pageUrl: "/resources/application-cases", aspect: "16:9" },
  { slot: "resources:application-cases-food-service", label: "应用案例 - 餐饮服务", page: "应用案例", pageUrl: "/resources/application-cases", aspect: "16:9" },
  { slot: "resources:application-cases-logistics", label: "应用案例 - 物流仓储", page: "应用案例", pageUrl: "/resources/application-cases", aspect: "16:9" },
  { slot: "resources:application-cases-healthcare", label: "应用案例 - 医疗", page: "应用案例", pageUrl: "/resources/application-cases", aspect: "16:9" },
  { slot: "resources:application-cases-parking", label: "应用案例 - 停车场", page: "应用案例", pageUrl: "/resources/application-cases", aspect: "16:9" },
  { slot: "resources:application-cases-banking", label: "应用案例 - 银行金融", page: "应用案例", pageUrl: "/resources/application-cases", aspect: "16:9" },

  // ===== 联系我们 =====
  { slot: "contact:hero", label: "联系我们 顶部图", page: "联系我们", pageUrl: "/contact", aspect: "16:9" },

  // ===== Till Rolls 聚合页 - 按尺寸卡片图（admin 可单独换图）=====
  { slot: "till-rolls:size:80x80mm", label: "Till Rolls 卡片图 - 80x80mm", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3" },
  { slot: "till-rolls:size:57x50mm", label: "Till Rolls 卡片图 - 57x50mm", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3" },
  { slot: "till-rolls:size:80x70mm", label: "Till Rolls 卡片图 - 80x70mm", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3" },
  { slot: "till-rolls:size:110x80mm", label: "Till Rolls 卡片图 - 110x80mm", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3" },
  { slot: "till-rolls:size:57x40mm", label: "Till Rolls 卡片图 - 57x40mm", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3" },
  { slot: "till-rolls:size:57x30mm", label: "Till Rolls 卡片图 - 57x30mm", page: "Till Rolls", pageUrl: "/products/till-rolls", aspect: "4:3" },
] as const satisfies readonly ImageSlot[];

/** 全部 slot key 的 union type — 编译期防止拼错 */
export type SlotKey = (typeof IMAGE_SLOTS)[number]["slot"];

/** 按页面分组（后台展示用） */
export function groupSlotsByPage(): Record<string, ImageSlot[]> {
  return IMAGE_SLOTS.reduce((acc, slot) => {
    if (!acc[slot.page]) acc[slot.page] = [];
    acc[slot.page].push(slot);
    return acc;
  }, {} as Record<string, ImageSlot[]>);
}

/** Set 形式，运行时检查 */
export const SLOT_KEYS = new Set<string>(IMAGE_SLOTS.map((s) => s.slot));
